variables:
  sln: msgpack.sln
  tests: tests/msgpack.light.tests/msgpack.light.tests.csproj

resources:
  repositories:
    - repository: templates
      type: github
      name: progaudi/azure-pipelines
      endpoint: progaudi

jobs:
- template: library/nuget.yml@templates
